collector:
  kafka:
    producer:
      properties:
        "[bootstrap.servers]": ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
        "[client.id]": telemetry.collector
        "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
        "[value.serializer]": ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
      topics:
        sensors-events: telemetry.sensors.v1
        hubs-events: telemetry.hubs.v1
