aggregator:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer-group-id: "aggregator"
    sensors-topic: "telemetry.sensors.v1"
    snapshots-topic: "telemetry.snapshots.v1"
    poll-timeout: 500ms

    consumer:
      enable.auto.commit: "false"
      auto.offset.reset: "earliest"

    producer:
      acks: "all"
      linger.ms: "5"